### PR TITLE
Initial support for BPMN escalation boundary event on CallActivity tasks

### PR DESCRIPTION
**Pull request by demostenes**
Escalation boundary events attached to CallActivity tasks will be activated if subworkflow embedded in CallActivity reaches any escalation end event node.

Boundary events with and without escalation code filter are supported in both interrupting and non-interrupting variants.

### CODE REVIEW

**Comment by demostenes** [comment]
I just pushed one last commit after fixing a new error manifesting itself intermittently, depending on the specific order the engine decided to complete available tasks.

**Comment by knipknap** [comment]
Hmmm, I am somewhat worried about the last commit. If `save_restore()` causes things to fail, there is almost certainly an underlying issue that needs to be fixed. Do you have a test case to show the failure?

**Comment by demostenes** [comment]
Actually, calling `save_restore()` caused the tests to pass when they shouldn't. If you revert that last commit and remove `save_restore()` calls from my tests then they will fail. At least they did on my machine :)

It seems to me that restored workflow completes available READY tasks in a slightly different order than a "fresh" one - in this case it completed BoundaryEvent node before finishing processing its parent (in the BPMN sense) CallActivity. Normally it's the other way around - CallActivity is completed first which causes `_BoundaryEventParent._child_complete_hook()` to `cancel()` the BoundaryEvent even if it's READY to run.

My last commit makes sure that BoundaryEvent is completed whenever it's triggered to protect it from being cancelled. This version passes the tests with and without `save_restore()` calls.

**Comment by demostenes** [comment]
I added a new test case to show that everything is working with and without `save_restore()`

**Comment by demostenes** [comment]
Can I do anything else to make this patch more safe to merge?

**Pull request merged**
