### PR TITLE
A year of BPMN / DMN Enhancements

### PR DESCRIPTION
**Pull request by danfunk**
I'm working on a project that hopes to use SpiffWorkflow to build out a multi-purpose tool for managing some complex workflow tasks for a university.   We'd like to support the open source Camunda modeler for creating BPMN diagrams as well.  I think this is general purpose enough to be of benefit to a wider community.  I wanted to get this in front of you to see if these are additions you believe would be good for SpiffWorkflow, or if I should attempt to create a separate companion project.  

This initial effort is just adding in a basic form processor.  But in the future I'd like to support the BMN notation for handing basic business rule definitions.  Rather than author detailed documentation for the main project, I'd also like to build out that documentation here, and write tutorials on creating BPMN diagrams and using them to execute a workflow.   Delve into serialization for storage and communication over an API, etc ....

### CODE REVIEW

**Comment by knipknap** [comment]
Wow! This looks like a very useful addition. I am wondering whether all these features are Camunda-proprietary, or whether they might be better implemented by just updating the existing BPMN model?

It also seems that this breaks existing unit tests...

Since I am not regularily checking this repo anymore, I can add you as a contributor and you can make any changes as you see fit.

**Comment by Mabloq** [comment]
Hey all, I am also trying to use Camunda's BMPN js model editor viewer with SpiffWorks. Any Docs on how to do this yet? Before I dive blind?

**Comment by danfunk** [comment]
@knipknap  - So we have charged forward with a large number of changes, while trying to keep all the original tests passing.  Is there any way we could talk you into hoping on a video chat with us next week and spending an hour looking at what we have done, where we are headed, and helping us think through some refactoring efforts to help simplify our additions?

**Comment by danfunk** [comment]
> Hey all, I am also trying to use Camunda's BMPN js model editor viewer with SpiffWorks. Any Docs on how to do this yet? Before I dive blind?

@Mabloq  - we have been heads down on a project that is built on top of Spiffworkflow, adding features and bug fixes as needed to fully support everything.  While we have added a significant number of tests that provide insight into what we have added, we have let the documentation fall grossly behind.  If you were up for helping us document this, I'd be glad to donate time in kind to helping get you up to speed on how we are using this framework and answering your questions.

**Comment by Mabloq** [comment]
> > Hey all, I am also trying to use Camunda's BMPN js model editor viewer with SpiffWorks. Any Docs on how to do this yet? Before I dive blind?
> 
> @Mabloq - we have been heads down on a project that is built on top of Spiffworkflow, adding features and bug fixes as needed to fully support everything. While we have added a significant number of tests that provide insight into what we have added, we have let the documentation fall grossly behind. If you were up for helping us document this, I'd be glad to donate time in kind to helping get you up to speed on how we are using this framework and answering your questions.

Hi, thanks for reaching out. I think I would like to do this. I haven't ever contributed to open source, but am interested. I am a junior dev with little experience, but since it just contributing documentation I feel comfortable helping out in this area.

**Pull request merged**
