### PR TITLE
fix: subworkflow script_engine not available after deserialize

### PR DESCRIPTION
**Pull request by mguikema**

### CODE REVIEW

**Comment by danfunk** [comment]
Hey!  Thanks for the pull request!

We didn't run into this as we use the BpmnWorkflow class, which assures we always have a script engine.   There is definitely some errors in our code, in that ScriptTask assumes we have a workflow with a script_engine, but the script_engine isn't defined on the Workflow class, it is set on the BpmnWorkflow class instead.  

I wonder about this proposed logic.  Do we really want to force the sub-workflow to always use the parent's script engine, even if it has one itself?   It would seem better to resolve this during the deserialization and assure that when deserialzing the sub-workflow we pick up the correct engine, or set it correctly.  

I'd love to see a test case that describes the problem, so I can understand how you are setting this up.  Do you have a BpmnWorkflow and that then contains a non-Bomn Workflow sub-process?

**Comment by mguikema** [comment]
Hi, this solution is a quick response on the issue when I ran into it. It should at least look at more outer_workflows, higher up in the hierarchy. But you are right, if the BpmnScriptEngine will be injected when the deserialization takes place, the outer_workflow checks can be avoided, and the solution would be much cleaner.

I will make a setup where the the problem accurse. But I defined my sub-process in a bpmn file.  At least this is the way I used your workflow engine. I don't if that changes thinks?

By the way, we are very happy you created the engine. It really does work as it should and predictable. Thanks a lot.

**Comment by mguikema** [comment]
Run the included .py in the .zip. It restores the .js and tries to run the custom script. It should output the following exception: Activity_00bzklw: something you are referencing does not exist: "name 'my_custom_function' is not defined". Did you mean '['common_formfield1']'?
[ExampleCode-Sub-save-restore-custom-script.zip](https://github.com/sartography/SpiffWorkflow/files/7116084/ExampleCode-Sub-save-restore-custom-script.zip)

**Comment by danfunk** [comment]
Took a look at this issue last night, the example is very helpful.  I haven't forgotten about this, it's just been a busy week.  I'll either come up with a solution that handles this during deserialization, or merge your change in, but we'll get this straightened out shortly.

**Comment by danfunk** [comment]
Fixed as a part of #130

**Pull request closed without merging**
